export const advertisingPackages = [
  {
    id: "brand-spotlight",
    name: "Brand Spotlight",
    price: "$299",
    priceSuffix: "/month",
    badge: "MOST VISIBLE",
    featured: true,
    description:
      "Put your brand in front of the AEC community with premium exposure across the Architecture Events platform and social media channels.",
    label: "INCLUDES:",
    details: [
      "Featured placement in the Brand Spotlight section on the homepage",
      "Company logo and featured image",
      "Company overview (100–200 words)",
      "Direct link to your website",
      "Call-to-action button",
      "One dedicated Instagram feed post",
      "One Instagram Story",
      "One LinkedIn feature/post",
      "Featured Brand designation for the month",
    ],
    note: "Limited to 4 companies per month.",
    buttonLabel: "Get Started",
    buttonVariant: "solid",
  },
  {
    id: "sponsored-reel",
    name: "Sponsored Reel",
    price: "$199",
    priceSuffix: "one-time",
    badge: null,
    featured: false,
    description:
      "Showcase your company, product, project, or event through a dedicated Instagram Reel.",
    label: "INCLUDES:",
    details: [
      "One Instagram Reel",
      "Company tagging (when applicable)",
      "Promotion through the Architecture Events Instagram account",
    ],
    note: null,
    buttonLabel: "Get Started",
    buttonVariant: "outline",
  },
  {
    id: "industry-partnership",
    name: "Industry Partnership",
    price: "Starting at $499",
    priceSuffix: "",
    badge: null,
    featured: false,
    description:
      "Create a customized marketing campaign designed to maximize your company's visibility within the AEC community.",
    label: "PARTNERSHIPS MAY INCLUDE:",
    details: [
      "Brand Spotlight",
      "Instagram promotion",
      "LinkedIn promotion",
      "Event promotion before, during, and after your event",
      "Event recap coverage",
      "Dedicated landing page",
      "Custom marketing campaigns",
      "Priority exposure across the platform",
    ],
    note:
      "Every partnership is customized based on your marketing goals and campaign objectives.",
    buttonLabel: "Contact Us for a Custom Proposal",
    buttonVariant: "outline",
  },
  {
    id: "founding-partner",
    name: "Founding Partner",
    price: "$999",
    priceSuffix: "/year",
    badge: null,
    featured: false,
    description:
      "Become one of the first companies to support Architecture Events and be recognized as a Founding Partner.",
    label: "INCLUDES:",
    details: [
      "Founding Partner recognition on the website",
      "Quarterly Brand Spotlight (4 per year)",
      "Quarterly Instagram feature",
      "Quarterly LinkedIn feature",
      "Company logo displayed in the Founding Partners section",
      "Priority consideration for future promotional opportunities",
    ],
    note: "Limited to the first 10 partners.",
    buttonLabel: "Become a Founding Partner",
    buttonVariant: "outline",
  },
] as const;
